[tool.poetry]
name = "Graph visualiser"
version = "0.1.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12.4"
networkx = "^3.4.2"
matplotlib = "^3.9.2"
pyqt6 = "^6.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
